### ISSUE TITLE
No output?

### ISSUE THREAD

**Issue by jas8522** [SpiderLabs/modsec-sdbm-util#14]
When I run this I get no output at all no matter which flag I use, including -d...

What am I missing?

We're seeing large ip.pag files (many GB in size) on our medium-to-high traffic servers and I'm attempting to find out if the Plesk build of mod_security suffers from the bug regarding not removing expired items from the DB. So I'm trying to run this utility to find out... but nada!

**Comment by bostrt** [comment]
@jas8522 Are you using the latest from the master branch? Can you show us the output of:

```
modsec-sdbm-util -u -s -d -v <database-name>
```

Also, if there's still no real output, `strace` might be a useful tool (assuming you are using Linux) to see if modsec-sdbm-util is actually reading in the database.

**Comment by jas8522** [comment]
Sorry, stupid mistake: didn't supply the database path/name as an argument.

**Comment by nitriques** [comment]
> Sorry, stupid mistake: didn't supply the database path/name as an argument.

I might be a good idea to add a usage line in the help/readme

usage: `modsec-sdbm-util [nkxsdahvurD] <DB name>`

I got caught by the same mistake.

**Comment by jas8522** [comment]
Indeed! Or perhaps it could try some of the common default dirs, then throw an error indicating that the database path and name was not supplied.

**Comment by zimmerle** [comment]
Fixed by @bostrt at 05ab469970576524d17ca36b303e96208ec5075c

**Comment by nitriques** [comment]
LGTM!

**Comment by nitriques** [comment]
I might find me picky, but now, `./modsec-sdbm-util -v` does not display anything. Not all option requires the database parameter ;)
