### ISSUE TITLE
"shrink" is incorrect

### ISSUE THREAD

**Issue by marcstern** [SpiderLabs/modsec-sdbm-util#3]
-k doesn't "shrink" the DB but only cleans up the entries. The file still has the same size. The help text should be adapted.
Isn't there any way to really shrink the file in-place?

**Comment by estrabd** [comment]
This issue is affecting us also.

**Comment by bostrt** [comment]
@marcstern you are correct in that the file size does not change even though entries are reaped with `-k`. I believe this is a design of DBM and the only way to decrease the size of the actual database file is to do a "reorganize". (do not quote me on the design of DBM, I can't really find a decent reference)

```
# modsec-sdbm-util /var/lib/mod_security/default_SESSION -n
Opening file: /var/lib/mod_security/default_SESSION
Database ready to be used.
New database generated with valid keys at: /tmp/new_db
```

**Comment by sbraz** [comment]
@bostrt Does that write the updated database in-place of the existing one?

**Comment by bostrt** [comment]
@sbraz Nope, the `-n` flag will write out to a new database file.

**Comment by estrabd** [comment]
We found -k useless. Instead, we use -n in combination of the -D that was merged recently, we then externally mv the old db files out of the way and replace them with the new files.

**Comment by bostrt** [comment]
@estrabd agreed, `-k` does not have a lot of use especially since a major gc issue was resolved in https://github.com/SpiderLabs/ModSecurity/pull/836

I expect it was kept around for debug purposes

**Comment by zimmerle** [comment]
Closing this issue. Vide @bostrt comment about the ```-n```` utilization.
